spring.application.name=ChatPrivado

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

URL_API = dasdasjdjas
UPLOAD_PRESET =