spring.application.name=ChatPrivado

spring.datasource.url=jdbc:postgresql://localhost:5433/ChatPrivado
spring.datasource.username=postgres
spring.datasource.password=minhasenha123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret = fjisdfwefiwfoweiqrwerwehuorouhewruhwehrweuruweurwehuruwehrhuweruwef
jwt.expiration = 5000000000
URL_API = https://api.cloudinary.com/v1_1/dcvnvdjlb/image/upload
UPLOAD_PRESET = ml_default